spring:
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        #nacos地址
        server-addr: 127.0.0.1:8848
        #指定名称空间
        namespace: 747695a5-8f62-4a66-b93a-fb296f235a3a
        #指定集群名称
        cluster-name: SH
        #服务实例元数据 [同一个服务的隔离实现]
        metadata:
          instance: SH113
    sentinel:
      filter:
        enabled: false
      transport:
        port: 8720
        dashboard: 127.0.0.1:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

server:
  port: 8010

#日志级别配置
logging:
  level:
    root: info
    com.sola.contentcenter.feignClicnet.UserCenterClient: debug
  pattern:
    console: '%p%m%n'

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      logic-not-delete-value: 0
      logic-delete-value: 1

#配置user-center负载规则
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon饥饿加载 指定微服务的BalancerRule项目启动时加载
#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-center

#feign配置
feign:
  sentinel:
    #为feign整合sentinel
    enabled: true
  client:
    config:
      default:
        loggerLevel: basic
  httpclient:
    #让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    #配置连接池提上feign性能 feign的最大请求数
    max-connections: 400
    #feign单个路径的最大请求数
    max-connections-per-route: 30
#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group