spring:
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  port: 8010

nacos:
  discovery:
    #nacos地址
    server-addr: XXX
    #指定名称空间
    namespace: XXX
    #指定集群名称
    cluster-name: XXX
    #服务实例元数据 [同一个服务的隔离实现]
    metadata:
      instance: UI989



logging:
  level:
    root: info
    com.sola.mybatis_plus_demo.dao.user: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      logic-not-delete-value: 0
      logic-delete-value: 1